env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  no-console: 0,
  semi: 2,
  eqeqeq: 2,
  curly: [error, all],
  no-unused-vars: 0,
  '@typescript-eslint/no-unused-vars':
    [warn, { vars: all, args: all, argsIgnorePattern: '^_', varsIgnorePattern: '^_' }]
}
