Options:
  widgets:
    - type: checkbox
      attribute: bail
      label: Bail on first failure

Input Values:
  widgets:
    - type: table
      attribute: values
      widgets:
        - type: text
          label: Name
        - type: text
          label: Value
        - type: checkbox
          label: Required
        - type: text
          label: Required If

Return Values:
  widgets:
    - type: table
      attribute: return
      widgets:
        - type: text
          label: Name
        - type: text
          label: Expression
