Subflow:
  widgets:
    - type: file
      label: Subflow
      attribute: subflow
      action: Select Flow

In Values:
  widgets:
    - type: table
      multi: false
      attribute: inValues
      widgets:
        - type: text
          label: Subflow Value Name
        - type: text
          label: Expression

Out Values:
  widgets:
    - type: table
      multi: false
      attribute: outValues
      widgets:
        - type: text
          label: Return Value Name
        - type: text
          label: Flow Value Name
