Subflow:
  widgets:
    - type: file
      label: Subflow
      attribute: subflow
      action: Select Flow
Flow Values:
  widgets:
    - type: table
      multi: false
      attribute: values
      widgets:
        - type: text
          label: Name
        - type: text
          label: Expression
