Subflow:
  widgets:
    - type: file
      label: Subflow
      attribute: subflow
      action: Select Flow

In Values:
  widgets:
    - type: table
      multi: false
      attribute: inValues
      widgets:
        - type: text
          label: Subflow Value
          readonly: true
        - type: text
          label: Expression or Static Text

Out Values:
  widgets:
    - type: table
      multi: false
      attribute: outValues
      widgets:
        - type: text
          label: Return Value
          readonly: true
        - type: text
          label: Flow Value Name
